### ISSUE TITLE
Add Event Deletion

### ISSUE THREAD

**Issue by Daniel-Dragon** [BIGJNO518/DPS-Backend#22]
In accordance with [The API](https://github.com/Dan-Baba/DPS-FrontEnd/wiki/API) events should be able to be deleted by marking the isDeleted field. Should also fix the get events by checking that isDeleted is false.

### Requirements
1. Add endpoint to delete event.
2. Fix getting events by checking for isDeleted column.

**Comment by marine1corps** [comment]
https://github.com/BIGJNO518/DPS-Backend/commit/7ada04ff7aa2a89cdbefcf60ce497569f6b142c4
